#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it.
file_name="$(date +%d-%m-%Y).tar.gz"
mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -cvzf "$file_name".tar.gz backup.sql
