#!/usr/bin/env bash
#script 101-manage_my_process that manages manage_my_process.

if [ "$1" == "start" ]
then
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ "$1" == "restart" ]
then
    pkill -SIGTERM -f "./manage_my_process"
    rm /var/run/my_process.pid
    rm /tmp/my_process
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"
elif [ "${1}" == "stop" ]
then
    echo "manage_my_process stopped"
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
