#!/usr/bin/env bash
#script that displays the content of the file /etc/passwd, using the while loop + IFS.

file="/etc/passwd"

while IFS=":" read -r un pw uid gid info hdir shell
do
    echo "The user $un is part of the $gid gang, lives in $hdir and \
rides $shell. $uid's place is protected by the passcode $pw, \
more info about the user here: $info"
done < "$file"
