#!/usr/bin/env bash
#script that configures an Ubuntu server with the below requirements.
#Requirements:
#
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts.new
echo "127.0.0.2\t\t\tlocalhost\n8.8.8.8\t\t\tfacebook.com\n" > ~/hosts.new
cp -f ~/hosts.new /etc/hosts
