#!/usr/bin/env bash
# ginx must be running as nginx user and listen to port 8080
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
